{{- with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ajensen-client.name" $ }}-svc
spec:
  type: ClusterIP
  selector:
    {{- include "ajensen-client.selectorLabels" $ | nindent 6 }}
  ports:
  - port: {{ .port }}
    targetPort: {{ default .port .containerPort }}
    name: {{ .name }}
    protocol: {{ default "TCP" .protocol }}
{{- end }}
